/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * employeedetails.java
 *
 * Created on Oct 12, 2011, 11:28:39 AM
 */
package UIcomponents;
import java.util.Vector;
import dbconnect.DBquery;
import java.sql.ResultSet;
import javax.swing.*;
/**
 *
 * @author user
 */
public class employeedetails extends javax.swing.JPanel {
    private Vector<Vector<String>> data;
    private Vector<String> header;
    /** Creates new form employeedetails */
    public employeedetails() {
        data = new Vector<Vector<String>>();
        try{
             DBquery d = new DBquery();
             ResultSet rs = d.generalQuery("SELECT * FROM test3");
             while(rs.next()){
                 Vector<String> row = new Vector<String>();
                 row.add(rs.getString(1));
                 row.add(rs.getString(2));
                 data.add(row);
             }
             header = new Vector<String>();
             header.add("Employee ID");
             header.add("Project ID");
        }catch(Exception e){
            System.out.println("test exception caught");
            e.printStackTrace();
        }
        
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        searchbutton = new javax.swing.JButton();
        logoutbutton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int vColIndex){
                return false;
            }
        };

        jLabel1.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("Employee Details");

        searchbutton.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        searchbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UIcomponents/Search_icon.png"))); // NOI18N
        searchbutton.setText("Search");

        logoutbutton.setFont(new java.awt.Font("Cooper Black", 0, 12));
        logoutbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UIcomponents/logout.gif"))); // NOI18N
        logoutbutton.setText("Logout");
        logoutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbuttonActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Arial Unicode MS", 0, 13));
        jTable1.setForeground(new java.awt.Color(0, 51, 153));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(data,header));
        jScrollPane1.setViewportView(jTable1);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(searchbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 331, Short.MAX_VALUE)
                                .addComponent(logoutbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addContainerGap(221, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {logoutbutton, searchbutton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutbutton)
                    .addComponent(searchbutton))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {logoutbutton, searchbutton});

    }// </editor-fold>//GEN-END:initComponents

private void logoutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbuttonActionPerformed
// TODO add your handling code here:
    data = new Vector<Vector<String>>();
    try{
             DBquery d = new DBquery();
             ResultSet rs = d.generalQuery("SELECT * FROM test3 WHERE proid = 1");
             while(rs.next()){
                 Vector<String> row = new Vector<String>();
                 row.add(rs.getString(1));
                 row.add(rs.getString(2));
                 data.add(row);
             }
             header = new Vector<String>();
             header.add("Employee ID");
             header.add("Project ID");
             jTable1.setModel(new javax.swing.table.DefaultTableModel(data,header));
        }catch(Exception e){
            System.out.println("test exception caught");
            e.printStackTrace();
        }
    
}//GEN-LAST:event_logoutbuttonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton logoutbutton;
    private javax.swing.JButton searchbutton;
    // End of variables declaration//GEN-END:variables
}

class test3{
    public static void main(String args[]){
        JFrame f = new JFrame();
        employeedetails e = new employeedetails();
        e.setVisible(true);
        f.add(e);
        f.pack();
        f.show();
    }
}
