/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * employeedetails.java
 *
 * Created on Oct 12, 2011, 11:28:39 AM
 */
package UIcomponents;
import java.util.Vector;
import dbconnect.DBquery;
import java.sql.ResultSet;
import javax.swing.*;
/**
 *
 * @author user
 */
public class employeedetails extends javax.swing.JPanel {
    private static Vector<Vector<String>> data;
    private static Vector<String> header;
    public static String searchstring;
    public static String searchcategory;
    private static javax.swing.table.DefaultTableModel model;
    /** Creates new form employeedetails */
    public employeedetails() {
        data = new Vector<Vector<String>>();
        try{
             DBquery d = new DBquery();
             ResultSet rs = d.generalQuery("SELECT emp_name,proj_name,EXTRACT(year from (sysdate))-EXTRACT(year from joindate) as experience,phone "
                     + "FROM employee,project,allocated_employees WHERE allocated_employees.empid = employee.emp_id AND allocated_employees.pid = project.proj_id");
             while(rs.next()){
                 Vector<String> row = new Vector<String>();
                 row.add(rs.getString(1));
                 row.add(rs.getString(2));
                 row.add(Integer.toString(rs.getInt(3)));
                 row.add(rs.getString(4));
                 data.add(row);
             }
             header = new Vector<String>();
             header.add("Employee Name");
             header.add("Project Name");
             header.add("Experience");
             header.add("Phone No.");
        }catch(Exception e){
            System.out.println("test exception caught");
            e.printStackTrace();
        }
        
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        searchbutton = new javax.swing.JButton();
        logoutbutton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int vColIndex){
                return false;
            }
        };

        jLabel1.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("Employee Details");

        searchbutton.setFont(new java.awt.Font("Cooper Black", 0, 12));
        searchbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UIcomponents/Search_icon.png"))); // NOI18N
        searchbutton.setText("Search");
        searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbuttonActionPerformed(evt);
            }
        });

        logoutbutton.setFont(new java.awt.Font("Cooper Black", 0, 12));
        logoutbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UIcomponents/logout.gif"))); // NOI18N
        logoutbutton.setText("Logout");
        logoutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbuttonActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 51, 153));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(data,header));
        jScrollPane1.setViewportView(jTable1);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(searchbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 340, Short.MAX_VALUE)
                                .addComponent(logoutbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel1)
                        .addGap(225, 225, 225))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {logoutbutton, searchbutton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutbutton)
                    .addComponent(searchbutton))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {logoutbutton, searchbutton});

    }// </editor-fold>//GEN-END:initComponents
public static void updateTable(){
    data.clear();
    try{
             DBquery d = new DBquery();
             ResultSet rs = d.generalQuery("SELECT * FROM test3 WHERE proid = 1");
             while(rs.next()){
                 Vector<String> row = new Vector<String>();
                 row.add(rs.getString(1));
                 row.add(rs.getString(2));
                 data.add(row);
             }
             model.fireTableDataChanged();
        }catch(Exception e){
            System.out.println("test exception caught");
            e.printStackTrace();
        }
    
}
    
    
private void logoutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbuttonActionPerformed
// TODO add your handling code here:
    data.clear();
    try{
             DBquery d = new DBquery();
             ResultSet rs = d.generalQuery("SELECT * FROM test3 WHERE proid = 1");
             while(rs.next()){
                 Vector<String> row = new Vector<String>();
                 row.add(rs.getString(1));
                 row.add(rs.getString(2));
                 data.add(row);
             }
             /*header = new Vector<String>();
             header.add("Employee ID");
             header.add("Project ID");*/
             javax.swing.table.DefaultTableModel k = (javax.swing.table.DefaultTableModel)jTable1.getModel();
             k.fireTableDataChanged();
        }catch(Exception e){
            System.out.println("test exception caught");
            e.printStackTrace();
        }
    
    
    
}//GEN-LAST:event_logoutbuttonActionPerformed

private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbuttonActionPerformed
    //System.out.println(searchstring + "," + searchcategory);
    this.setEnabled(false);
    model = (javax.swing.table.DefaultTableModel)jTable1.getModel();
    Searchform s = new Searchform();
    s.setVisible(true);
    //System.out.println(searchstring + "," + searchcategory);
    
}//GEN-LAST:event_searchbuttonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton logoutbutton;
    private javax.swing.JButton searchbutton;
    // End of variables declaration//GEN-END:variables
}

class test3{
    public static void main(String args[]){
        JFrame f = new JFrame();
        employeedetails e = new employeedetails();
        e.setVisible(true);
        f.add(e);
        f.pack();
        f.show();
    }
}
