/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PRPanel.java
 *
 * Created on Oct 9, 2011, 7:38:19 AM
 * Test templates.
 */
package UIcomponents;
import java.sql.*;
import dbconnect.*;
import javax.swing.*;
import mini.*;

/**
 *
 * @author user
 */
public class PRPanel extends javax.swing.JPanel {

    /** Creates new form PRPanel */
    public PRPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlelabel = new javax.swing.JLabel();
        namelabel = new javax.swing.JLabel();
        qtylabel = new javax.swing.JLabel();
        qtyfield = new javax.swing.JTextField();
        submitbutton = new javax.swing.JButton();
        namecombo = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 255, 255));

        titlelabel.setFont(new java.awt.Font("Cooper Black", 0, 24));
        titlelabel.setForeground(new java.awt.Color(0, 51, 153));
        titlelabel.setText("Physical  Resource  Details");

        namelabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14));
        namelabel.setForeground(new java.awt.Color(0, 51, 153));
        namelabel.setText("Name");

        qtylabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14));
        qtylabel.setForeground(new java.awt.Color(0, 51, 153));
        qtylabel.setText("Quantity Available");

        qtyfield.setForeground(new java.awt.Color(0, 51, 153));
        qtyfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyfieldActionPerformed(evt);
            }
        });

        submitbutton.setFont(new java.awt.Font("Cooper Black", 0, 14));
        submitbutton.setForeground(new java.awt.Color(0, 51, 153));
        submitbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UIcomponents/submitIcon.gif"))); // NOI18N
        submitbutton.setText("Submit");
        submitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbuttonActionPerformed(evt);
            }
        });

        namecombo.setEditable(true);
        String[] lst = new String[10];
        try{
            DBquery d = new DBquery();
            ResultSet rs = d.generalQuery("SELECT DISTINCT res_name FROM phy_resource");
            System.out.println("testing");
            short i =0;
            while(rs.next()){
                System.out.println("testing again");
                lst[i] = rs.getString(1);
                System.out.println(lst[i]);
                i++;
            }
        }catch(Throwable e){
            System.out.println("test error");
        }
        namecombo.setModel(new javax.swing.DefaultComboBoxModel(lst));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(titlelabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(namelabel)
                                    .addComponent(qtylabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(qtyfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(namecombo, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(submitbutton)
                        .addGap(142, 142, 142))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {namelabel, qtylabel});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {namecombo, qtyfield});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titlelabel)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namelabel)
                    .addComponent(namecombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtyfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtylabel))
                .addGap(34, 34, 34)
                .addComponent(submitbutton)
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void qtyfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyfieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_qtyfieldActionPerformed

private void submitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbuttonActionPerformed

    try
    {
        
        String name = (String) namecombo.getSelectedItem();
        String Qty = qtyfield.getText();
  //      System.out.println("testing again");
        int qt = Integer.parseInt(Qty);
    //    System.out.println("testing 1");
        System.out.println(qt);
        System.out.println(name);
//         System.out.println("testing 2");
        
        if(name.length()==0|| Qty.length()==0 || qt==0)
        {
           
            JOptionPane.showMessageDialog(null,"Empty fields not allowed!!!","Fields Empty",
                    JOptionPane.WARNING_MESSAGE);
             throw(new Exception () );
        }
        DBquery db = new DBquery();
        ResultSet ra = db.generalQuery("SELECT * FROM phy_resource");
        short flag = 0;
        while(ra.next())
        {
            if(ra.getString(2).equals(name))
            {
                flag=1;
                DBinsert ab = new DBinsert();
                String statmnt;               
                statmnt="UPDATE phy_resource SET insta =insta + " + qt+ " WHERE res_name='" + ra.getString(2) + "'"; 
                System.out.println(statmnt);
                ab.generalInsert(statmnt);
                statmnt="UPDATE available_phy SET qty=qty + " + qt + " WHERE avail_resid=" + ra.getInt(1);
                ab.generalInsert(statmnt);            
                
            }
            
        }
        if(flag==0)
        {   String s;
       
            DBinsert av_phy=new DBinsert();
            Resource r = new Resource(name,qt);
            DBinsert ac =new DBinsert();
            ac.addResource(r);
            s="SELECT res_id FROM phy_resource WHERE res_name='" + name +"'";
            ResultSet phy_id=db.generalQuery(s);
            phy_id.next();
            s="INSERT INTO available_phy VALUES("+ phy_id.getInt(1) + "," + qt+ ")";
            av_phy.generalInsert(s);
            
        }
        
    }
    catch(NumberFormatException e)
    {
        JOptionPane.showMessageDialog(null,"Empty fields not allowed!!!","Fields Empty",
                    JOptionPane.WARNING_MESSAGE);
        System.out.println("Number format exception");
    }
    catch(Throwable e)
    {
        String errmsg = e.getMessage();
        if(errmsg == null || errmsg.length() == 0){
            errmsg = "Fatal : " + e.getClass();
        }
         e.printStackTrace();
           
    
          JOptionPane.showMessageDialog(null,errmsg,"ERROR!!!",JOptionPane.ERROR_MESSAGE);
    }
}//GEN-LAST:event_submitbuttonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox namecombo;
    private javax.swing.JLabel namelabel;
    private javax.swing.JTextField qtyfield;
    private javax.swing.JLabel qtylabel;
    private javax.swing.JButton submitbutton;
    private javax.swing.JLabel titlelabel;
    // End of variables declaration//GEN-END:variables
}

class tes{
    public static void main(String args[]){
        JFrame f = new JFrame();
        PRPanel p = new PRPanel();
        p.setVisible(true);
        f.add(p);
        f.pack();
        f.show();
        
    }
}