/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Rpanel.java
 *
 * Created on Oct 9, 2011, 7:26:01 AM
 */

package UIcomponents;
import javax.swing.*;
import mini.*;
import dbconnect.*;
import java.sql.*;

/**
 *
 * @author user
 */
public class Rpanel extends javax.swing.JPanel {

    private int jy;
    private int jm;
    private int jd;
    /** Creates new form Rpanel */
    public Rpanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        doblabel = new javax.swing.JLabel();
        agelabel = new javax.swing.JLabel();
        phonelabel = new javax.swing.JLabel();
        phne_field = new javax.swing.JTextField();
        addrlabel = new javax.swing.JLabel();
        addrfield = new javax.swing.JScrollPane();
        addr_area = new javax.swing.JTextArea();
        speclabel = new javax.swing.JLabel();
        submitbtn = new javax.swing.JButton();
        dayspin = new javax.swing.JSpinner();
        monthspin = new javax.swing.JSpinner();
        yearspin = new javax.swing.JSpinner();
        monthlabel = new javax.swing.JLabel();
        yearlabel = new javax.swing.JLabel();
        daylabel = new javax.swing.JLabel();
        jComboBox_spec = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        name_field = new javax.swing.JTextField();
        emp_id_field = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        title.setFont(new java.awt.Font("Cooper Black", 0, 24));
        title.setForeground(new java.awt.Color(0, 51, 153));
        title.setText("Employee    Details");

        doblabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        doblabel.setForeground(new java.awt.Color(0, 51, 153));
        doblabel.setText("Name");

        agelabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        agelabel.setForeground(new java.awt.Color(0, 51, 153));
        agelabel.setText("Join Date");

        phonelabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14));
        phonelabel.setForeground(new java.awt.Color(0, 51, 153));
        phonelabel.setText("Phone no");

        addrlabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14));
        addrlabel.setForeground(new java.awt.Color(0, 51, 153));
        addrlabel.setText("Address");

        addr_area.setColumns(20);
        addr_area.setRows(5);
        addrfield.setViewportView(addr_area);

        speclabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14));
        speclabel.setForeground(new java.awt.Color(0, 51, 153));
        speclabel.setText("Specialisation ");

        submitbtn.setFont(new java.awt.Font("Cooper Black", 0, 14));
        submitbtn.setForeground(new java.awt.Color(0, 51, 153));
        submitbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UIcomponents/submitIcon.gif"))); // NOI18N
        submitbtn.setText("Submit");
        submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtnActionPerformed(evt);
            }
        });

        dayspin.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        dayspin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                dayspinStateChanged(evt);
            }
        });

        monthspin.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        monthspin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                monthspinStateChanged(evt);
            }
        });

        yearspin.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(2000), Integer.valueOf(2000), null, Integer.valueOf(1)));
        yearspin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                yearspinStateChanged(evt);
            }
        });

        monthlabel.setText("Month");

        yearlabel.setText("Year");

        daylabel.setText("Day");

        String[] lst = new String[20];
        try{
            DBquery d = new DBquery();
            ResultSet rs = d.generalQuery("SELECT DISTINCT spec_name FROM specialisation");
            System.out.println("testing");
            short i =0;
            while(rs.next()){
                System.out.println("testing again");
                lst[i] = rs.getString(1);
                System.out.println(lst[i]);
                i++;
            }
        }catch(Throwable e){
            System.out.println("test error");
        }
        jComboBox_spec.setModel(new javax.swing.DefaultComboBoxModel(lst));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Employee ID");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        name_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_fieldActionPerformed(evt);
            }
        });

        emp_id_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_id_fieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(title)
                .addContainerGap(229, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(277, Short.MAX_VALUE)
                .addComponent(submitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(207, 207, 207))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doblabel)
                    .addComponent(phonelabel)
                    .addComponent(addrlabel)
                    .addComponent(speclabel)
                    .addComponent(agelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emp_id_field, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addComponent(name_field, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(daylabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(dayspin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(monthlabel)
                            .addGap(11, 11, 11)
                            .addComponent(monthspin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(yearlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(yearspin, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jComboBox_spec, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(phne_field)
                        .addComponent(addrfield, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)))
                .addGap(149, 149, 149))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addrlabel, doblabel, jLabel1, phonelabel, speclabel});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(emp_id_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doblabel)
                    .addComponent(name_field, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(agelabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(phonelabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(daylabel)
                            .addComponent(dayspin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(monthlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(monthspin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearlabel)
                            .addComponent(yearspin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(phne_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addrlabel)
                    .addComponent(addrfield, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(speclabel)
                    .addComponent(jComboBox_spec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(submitbtn)
                .addGap(26, 26, 26))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {doblabel, jLabel1});

    }// </editor-fold>//GEN-END:initComponents

private void submitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtnActionPerformed
    try{
        String name = name_field.getText();
        String empid = emp_id_field.getText();
        String phno = phne_field.getText();
        String emp_spec = (String) jComboBox_spec.getSelectedItem();
        String address = addr_area.getText();
        SpinnerNumberModel model1 = (SpinnerNumberModel)dayspin.getModel();
        SpinnerNumberModel model2 = (SpinnerNumberModel)monthspin.getModel();
        SpinnerNumberModel model3 = (SpinnerNumberModel)yearspin.getModel();
        int jd1 = model1.getNumber().intValue();
        int jm1 = model2.getNumber().intValue();
        int jy1 = model3.getNumber().intValue();
        int spec_id;
        DBquery retrieve_spec_id = new DBquery();
        String stat="SELECT spec_id FROM specialisation WHERE spec_name='"+
                emp_spec + "'" ;
        ResultSet result = retrieve_spec_id.generalQuery(stat);
        result.next();
        spec_id = result.getInt(1);
        DBquery retrieve_from_hr_avail = new DBquery();
        String retrive = " SELECT specid FROM hr_total_avail";
        ResultSet res = retrieve_from_hr_avail.generalQuery(retrive);
        short flag=0;
        String hr_update;
        while(res.next())
        {
            if(res.getInt(1)==spec_id)
            {   
                flag=1;
                hr_update="UPDATE hr_total_avail SET tot_qty= tot_qty + 1,avail_qty=avail_qty + 1 WHERE specid ="
                       + spec_id ;  
                DBcreate hr = new DBcreate();
                hr.Create_Other_Table(hr_update);
            }
        }
        if(flag==0)
        {
        DBinsert hr_avail_insert = new DBinsert();    
        String hr_availibility_update;
        hr_availibility_update = "INSERT INTO hr_total_avail VALUES(" +
                spec_id + ",1,1)";
        hr_avail_insert.generalInsert(hr_availibility_update);
            
        }
       
        flag=0;
        DBquery check_empid = new DBquery();
        ResultSet result_empid = check_empid.generalQuery("SELECT emp_id FROM employee");
        while(result_empid.next())
        {
        if(result_empid.getString(1).equals(empid)){
            flag=1;
        }
        }
        if(flag==1)
        {
            JOptionPane.showMessageDialog(null,"Employee ID exists give another..!!","Employee ID Error",
                    JOptionPane.WARNING_MESSAGE);
            throw(new Exception());
        }
            
        if(name == null||emp_spec == null||phno == null||address == null){
            JOptionPane.showMessageDialog(null,"Empty fields not allowed!!!","Fields Empty",
                    JOptionPane.WARNING_MESSAGE);
            throw(new Exception());
        }
        else if(name.length()==0||emp_spec.length()==0||phno.length()==0||address.length()==0){
            JOptionPane.showMessageDialog(null,"Empty fields not allowed!!!","Fields Empty",
                    JOptionPane.WARNING_MESSAGE);
            throw(new Exception());
        }
        double test = Double.parseDouble(phno);
        int status=0;
        Employee emp = new Employee(empid,name,address,spec_id,phno,jy1,jm1,jd1,status);
        DBinsert d = new DBinsert();
        d.addEmployee(emp);
    }catch(Throwable e){
        e.printStackTrace();
        String errmsg = e.getMessage();
        if(errmsg == null || errmsg.length() == 0){
            errmsg = "Fatal : " + e.getClass();
        }
        JOptionPane.showMessageDialog(null,"ERROR!!!",errmsg,JOptionPane.ERROR_MESSAGE);
    }
}//GEN-LAST:event_submitbtnActionPerformed

private void dayspinStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_dayspinStateChanged
   // JSpinner source = (JSpinner)evt.getSource();
   // jd = Integer.parseInt(source.getValue().toString());
    
}//GEN-LAST:event_dayspinStateChanged

private void monthspinStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_monthspinStateChanged
   // JSpinner source = (JSpinner)evt.getSource();
    //jm = Integer.parseInt(source.getValue().toString());
}//GEN-LAST:event_monthspinStateChanged

private void yearspinStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_yearspinStateChanged
    //JSpinner source = (JSpinner)evt.getSource();
    //jy = Integer.parseInt(source.getValue().toString());
}//GEN-LAST:event_yearspinStateChanged

private void name_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_fieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_name_fieldActionPerformed

private void emp_id_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_id_fieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_emp_id_fieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addr_area;
    private javax.swing.JScrollPane addrfield;
    private javax.swing.JLabel addrlabel;
    private javax.swing.JLabel agelabel;
    private javax.swing.JLabel daylabel;
    private javax.swing.JSpinner dayspin;
    private javax.swing.JLabel doblabel;
    private javax.swing.JTextField emp_id_field;
    private javax.swing.JComboBox jComboBox_spec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel monthlabel;
    private javax.swing.JSpinner monthspin;
    private javax.swing.JTextField name_field;
    private javax.swing.JTextField phne_field;
    private javax.swing.JLabel phonelabel;
    private javax.swing.JLabel speclabel;
    private javax.swing.JButton submitbtn;
    private javax.swing.JLabel title;
    private javax.swing.JLabel yearlabel;
    private javax.swing.JSpinner yearspin;
    // End of variables declaration//GEN-END:variables
}

class test{
    public static void main(String args[]){
        JFrame f = new JFrame();
        Rpanel p = new Rpanel();
        p.setVisible(true);
        f.add(p);
        f.pack();
        f.show();
        
    }
}